#!/bin/bash

VAR1=`echo $1`
VAR2=`echo $2`

#sum=`expr $VAR1 + $VAR2`
#sum=$(expr $VAR1 + $VAR2)
sum=$(($VAR1 + $VAR2))

echo "Sum of two numbers is $sum"
#!/bin/bash

echo "Enter the value of first number:"
read VAR1 VAR2

#echo "Enter the value of second number:"
#read VAR2

sum=`expr $VAR1 + $VAR2`

echo "Sum of the both number $VAR1 and $VAR2 is $sum"
